# Generated by Django 4.2 on 2023-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='img',
            field=models.ImageField(default='just', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
